//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriculas_ITM.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Matricula
    {
        public int idMatricula { get; set; }
        public int idEstudiante { get; set; }
        public int NumeroCreditos { get; set; }
        public int ValorCredito { get; set; }
        public int TotalMatricula { get; set; }
        public System.DateTime FechaMatricula { get; set; }
        public string SemestreMatricula { get; set; }
        public string MateriasMatriculadas { get; set; }
        [JsonIgnore]
        public virtual Estudiante Estudiante { get; set; }
    }
}
